name: Test Installing Plugins

# Test Top 50 asdf plugins install correctly and the most common can print their
# current version

on:
  release:
    types: [published]
  schedule:
    # run at midnight on sunday (utc?)
    - cron: 0 0 * * 0
  # TODO: Remove on pull_request once CI is verified to run correctly
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "x86_64-unknown-linux-gnu"
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-unknown-linux-gnu
      - run: scripts/build-tarball.sh x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: tarball-x86_64-unknown-linux-gnu
          path: |
            dist/rtx-*.tar.xz
            dist/rtx-*.tar.gz
          if-no-files-found: error
  test-install-and-run:
    name: Self Test popular plugins
    runs-on: ubuntu-22.04
    needs: [ build-linux ]
    continue-on-error: true
    env:
      RTX_MISSING_RUNTIME_BEHAVIOR: autoinstall
    strategy:
      matrix:
        include:
          - plugin: nodejs
            command: rtx exec nodejs@latest -- node -v
          - plugin: ruby
            command: rtx exec ruby@latest -- ruby --version
          - plugin: python
            command: rtx exec python@latest -- python -V
          - plugin: direnv
            command: rtx exec direnv@latest -- direnv --version
          - plugin: erlang
            command: rtx exec erlang@latest -- erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
          - plugin: elixir
            command: rtx exec elixir@latest erlang -- elixir --version
          - plugin: golang
            command: rtx exec golang@latest -- go version
          - plugin: java@openjdk
            command: rtx exec java@openjdk -- java -version
          - plugin: terraform
            command: rtx exec terraform@latest -- terraform -v
          - plugin: yarn
            command: rtx exec yarn@latest -- yarn --version
          - plugin: deno
            command: rtx exec deno@latest -- deno --version
          - plugin: bun
            command: rtx exec bun@latest -- bun --version
          - plugin: kubectl
            command: rtx exec kubectl@latest -- kubectl version --client
          - plugin: dotnet
            command: rtx exec dotnet@latest-core -- dotnet --list-sdks
          - plugin: flutter
            command: rtx exec flutter@latest -- flutter --version
          - plugin: crystal
            command: rtx exec crystal@latest -- crystal -v
          - plugin: neovim
            command: rtx exec neovim@latest -- nvim --version
          - plugin: php
            command: rtx exec php@latest -- php -v php
          - plugin: rust
            command: rtx exec rust@latest -- rustc -V
          - plugin: postgres
            command: rtx exec postgres@latest -- psql -v
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh/fish/direnv
        run: sudo apt-get update; sudo apt-get install zsh fish direnv
      - uses: actions/download-artifact@v3
        with:
          name: tarball-x86_64-unknown-linux-gnu
          path: dist
      - run: tar -C "$HOME" -xvJf dist/rtx-$(./scripts/get-version.sh)-linux-x64.tar.xz
      - run: echo "$HOME/rtx/bin" >> $GITHUB_PATH
      - run: rtx -v
      - run: ${{matrix.command}}
  test-install:
    runs-on: ubuntu-22.04
    needs: [ build-linux ]
    continue-on-error: true
    strategy:
      matrix:
        plugins: 
          - waypoint
          - vault
          - tfc-agent
          - terraform-ls
          - serf
          - sentinel
          - packer
          - nomad
          - levant
          - consul
          - boundary
          - php
          - postgres
          - rust
          - action-validator
          - dotnet-core
          - neovim
          - poetry
          - haskell
          - link
          - lua
          - redis
          - gcloud
          - helm
          - gleam
          - awscli
          - dart
          - conan
          - awsebcli
          - aws-sam-cli
          - ansible-base
          - kotlin
          - pnpm
          - ocaml
          - rebar
          - julia
          - elm
          - R
          - nim
          - alias
          - mysql
          - minikube
          - gradle
          - zig
          - shellcheck
          - scala
          - maven
          - kustomize
          - graalvm
          - sbcl
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh/fish/direnv
        run: sudo apt-get update; sudo apt-get install zsh fish direnv
      - uses: actions/download-artifact@v3
        with:
          name: tarball-x86_64-unknown-linux-gnu
          path: dist
      - run: tar -C "$HOME" -xvJf dist/rtx-$(./scripts/get-version.sh)-linux-x64.tar.xz
      - run: echo "$HOME/rtx/bin" >> $GITHUB_PATH
      - run: rtx install ${{matrix.plugins}}@latest